name: _

on:
  workflow_call:
    inputs: 
      createrelease:
        type: boolean
        default: false
        required: false 
jobs:
  cpps:
    runs-on: ${{matrix.runson}}
    strategy:
      matrix:
        work: ['hook', 'cpp']
        include:
          - arch: x86
            target: win7  
            runson: windows-latest
          - arch: x64
            target: win7  
            runson: windows-latest
          - arch: x64
            target: win10  
            runson: windows-latest
          - arch: x86
            target: win10  
            runson: windows-latest
          - arch: x86
            target: xp
            runson: windows-2019
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      - if: ${{matrix.work=='hook'}}
        run: python src/scripts/build_lunahook.py build ${{matrix.arch}} 1 ${{matrix.target}}
      - if: ${{matrix.work=='cpp'}}
        run:  python src/scripts/build_lunatranslator.py cpp ${{ matrix.arch }} ${{matrix.target}}

      - if: ${{matrix.work=='cpp'}}
        uses: actions/upload-artifact@v4
        with:
          name: cpp_${{matrix.arch}}_${{matrix.target}}
          path: src/cpp/builds
      - if: ${{matrix.work=='hook'}}
        uses: actions/upload-artifact@v4
        with:
          name: hook_${{matrix.arch}}_${{matrix.target}}
          path: src/cpp/LunaHook/builds/Release${{matrix.target=='xp' &&'_winxp'||''}}
  pyrt:
    runs-on: windows-latest
    strategy:
      matrix:
        include:  
          - arch: x86
            target: win7
            pythonversion: '3.7.9' 
          - arch: x64
            target: win7
            pythonversion: '3.7.9' 
          - arch: x64
            target: win10
            pythonversion: '3.12.10'  
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.pythonversion}}
          architecture: ${{ matrix.arch }}
      
      - run:  python src/scripts/build_lunatranslator.py pyrt ${{ matrix.arch }} ${{matrix.pythonversion}} ${{matrix.target}}

      - uses: actions/upload-artifact@v4
        with:
          name: pyrt_${{matrix.arch}}_${{matrix.target}}
          path: src/pyrt
  
  merge:
    runs-on: windows-latest
    needs: [pyrt,cpps]
    permissions:
      id-token: write
      attestations: write
      contents: write
    strategy:
      matrix:
        include:
          - arch: x86
            target: win7 
            savename: LunaTranslator_x86
          - arch: x64
            target: win7 
            savename: LunaTranslator
          - arch: x64
            target: win10 
            savename: LunaTranslator_win10 
    steps:
      - uses: actions/checkout@v4
      - run: git submodule init src/files/LunaTranslator_qss
      - run: git submodule update src/files/LunaTranslator_qss
      - uses: actions/download-artifact@v4
        with:
            path: build
      - run:  python src/scripts/build_lunatranslator.py merge ${{ matrix.arch }} ${{matrix.target}}
      - uses: actions/attest-build-provenance@v2.2.0
        with:
            subject-path: src/build/${{ matrix.savename }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.savename }}
          path: src/build/${{ matrix.savename }}.zip
  merge_xp:
    runs-on: windows-latest
    needs: [cpps]
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: git submodule init src/files/LunaTranslator_qss
      - run: git submodule update src/files/LunaTranslator_qss
      - uses: actions/download-artifact@v4
        with:
            path: build
      - run:  python src/scripts/build_lunatranslator.py merge x86 xp
      - uses: actions/attest-build-provenance@v2.2.0
        with:
            subject-path: src/build/LunaTranslator_x86_winxp.zip
      - uses: actions/upload-artifact@v4
        with:
          name: LunaTranslator_x86_winxp
          path: src/build/LunaTranslator_x86_winxp.zip
  loadversion:
    if: ${{inputs.createrelease}}
    runs-on: windows-latest
    outputs:
      version: ${{ steps.loadversion.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: loadversion
        run: python src/scripts/build_lunatranslator.py loadversion | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

  release:
    if: ${{inputs.createrelease}}
    runs-on: windows-latest
    needs: [merge_xp,merge,loadversion]
    steps:
      - uses: actions/download-artifact@v4
        with:
            path: build
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.loadversion.outputs.version }}
          files: |
            build/LunaTranslator_x86_winxp/LunaTranslator_x86_winxp.zip
            build/LunaTranslator_x86/LunaTranslator_x86.zip
            build/LunaTranslator/LunaTranslator.zip
          #  build/LunaTranslator_win10/LunaTranslator_win10.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
